### ISSUE TITLE
[Suggestion] New NET Core project format

### ISSUE THREAD

**Issue by ghost** [sesispla/docker-nginx-kestrel#2]
Hey, @sesispla ! Found this repo very useful, but not working.  
`dotnet restore`  
produces next error:
`MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
ERROR: Service 'core-app' failed to build: The command 'dotnet restore' returned a non-zero code: 1`

As I found, Microsoft changed project format at last NET Core release and project.json doesn't works anymore. 

There is a simple way to fix this:  
`dotnet migrate`

I've did it in my [Fork](https://github.com/johnsnowdies/docker-nginx-kestrel/commit/3eb614463ed1a0e08cece8e5ae28fa3d1aacc594)

Best regards,
Sergey

**Comment by sesispla** [comment]
Thank you @johnsnowdies I am going to pick it up and give it a try. This will definitely help fixing #3

**Comment by sesispla** [comment]
@johnsnowdies merged and updated to latest ASP.NET Core bits. Thx!
