### ISSUE TITLE
Not working on Windows

### ISSUE THREAD

**Issue by deqing** [sesispla/docker-nginx-kestrel#3]
```
> docker-compose build
Building core-app
Step 1/8 : FROM microsoft/dotnet
 ---> c7f0db36c01b
Step 2/8 : RUN printf "deb http://ftp.us.debian.org/debian jessie main\n" >> /etc/apt/sources.list
 ---> Running in 2a5417c85698
 ---> f64293d3ff07
Removing intermediate container 2a5417c85698
Step 3/8 : COPY . /app
 ---> 3e9f828e8286
Removing intermediate container 929481eaec4a
Step 4/8 : WORKDIR /app
 ---> 093e4c4e4a59
Removing intermediate container 9d1f6927824b
Step 5/8 : RUN dotnet restore
 ---> Running in 2b8a6898f772
MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
ERROR: Service 'core-app' failed to build: The command 'dotnet restore' returned a non-zero code: 1
```

**Comment by sesispla** [comment]
Hello @deqing,

This example was built with old ASP.NET Core bits. 

I am going to upgrade it to .NET Core 1.1

**Comment by sesispla** [comment]
@deqing updated to latest ASP.NET Core stable bits (1.1.2) and tested on both Windows (Docker for Windows) and Mac OS X (Boot2Docker).

Enjoy!

<img width="1231" alt="screen shot 2017-05-27 at 14 58 45" src="https://cloud.githubusercontent.com/assets/8591052/26521630/58df423a-42ed-11e7-9cd0-53657f6a20ed.png">
<img width="955" alt="screen shot 2017-05-27 at 15 01 20" src="https://cloud.githubusercontent.com/assets/8591052/26521632/5ed80cf8-42ed-11e7-8a2c-40366da7db43.png">

**Comment by deqing** [comment]
@sesispla thanks!
